### ISSUE TITLE
Error with perl bindings

### ISSUE THREAD

**Issue by Chayyoo** [s-yata/marisa-trie#13]
Marisa works well on my local machine (perl 5.22). But on a machine with CentOS6 (perl 5.10.1) I get the following error:
perl sample.pl 
Can't load '/usr/local/lib64/perl5/auto/marisa/marisa.so' for module marisa: /usr/local/lib64/perl5/auto/marisa/marisa.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE at /usr/lib64/perl5/DynaLoader.pm line 200.
 at /usr/local/lib64/perl5/marisa.pm line 11
Compilation failed in require at sample.pl line 1.
BEGIN failed--compilation aborted at sample.pl line 1.

Any suggestions?
(PS had to upgrade to newer versions of autoconf and automake in order to compile marisa on CentOS6).

**Comment by s-yata** [comment]
Sorry, I have no idea.

**Comment by s-yata** [comment]
I can reproduce a similar (or the same?) problem on Fedora 41.

```
~/github.com/s-yata/marisa-trie/bindings/perl$ perl sample.pl 
Can't load '/usr/local/lib64/perl5/5.40/auto/marisa/marisa.so' for module marisa: libmarisa.so.0: cannot open shared object file: No such file or directory at /usr/lib64/perl5/DynaLoader.pm line 206.
 at /usr/local/lib64/perl5/5.40/marisa.pm line 11.
Compilation failed in require at sample.pl line 1.
BEGIN failed--compilation aborted at sample.pl line 1.
```

**Comment by s-yata** [comment]
After manually setting `LD_LIBRARY_PATH`, it works.

```
~/github.com/s-yata/marisa-trie/bindings/python3$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

~/github.com/s-yata/marisa-trie/bindings/python3$ python3 sample.py 
no. keys: 4
no. tries: 3
no. nodes: 6
size: 4104
cake: 1
cookie: 2
cockoo: not found
ice: 0
ice-cream: 3
ice-age: not found
0: ice
1: cake
2: cookie
3: ice-cream
ice-cream soda: ice (0)
ice-cream soda: ice-cream (3)
ic: ice (0)
ic: ice-cream (3)
```

**Comment by s-yata** [comment]
Oops, it's a mistake. It was bindings for Python...

Perl bindings  and Ruby bindings work as well.

**Comment by s-yata** [comment]
`/etc/ld.so.conf` or `/etc/ld.so.conf.d/local.conf` is also available.

I'm not sure what is the **correct** way to solve this problem...

Libraries should be installed in another directory?
`LD_LIBRARY_PATH`, `ld.so.conf` or any other way?
